module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'gateway',
        'transactions',
        'crm',
        'documents',
        'notifications',
        'social',
        'billing',
        'ai-docs',
        'ai-copilot',
        'ai-assist',
        'ai-media',
        'ai-marketing',
        'compliance',
        'preference-engine',
        'esign',
        'media-encoder',
        'web',
        'mobile',
        'ui',
        'types',
        'config',
        'utils',
        'db',
        'proto',
        'infra',
        'ci',
        'deps',
        'api',
      ],
    ],
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'test', 'chore', 'refactor', 'security', 'perf', 'ci', 'build'],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
