-- Migration: 0085_phase10_seed_help_articles.sql
-- Phase 10: CrestAI Copilot & CrestAssist — Seed Help Articles

INSERT INTO help_articles (tenant_id, slug, title, summary, content, category, feature_area, applicable_roles, tags, sort_order) VALUES

-- Getting Started
(NULL, 'getting-started-overview', 'Welcome to CrestDesk', 'A quick overview of CrestDesk and how to get started.', E'# Welcome to CrestDesk\n\nCrestDesk is your all-in-one real estate transaction management platform. Here''s how to get started:\n\n1. **Complete your profile** — Add your photo, phone number, and license information in Settings\n2. **Connect your email** — Link Gmail or Outlook with one-click OAuth in Email Settings\n3. **Import contacts** — Bring in your existing contacts from CSV or another CRM\n4. **Explore the dashboard** — Your daily action cards show what needs attention today\n\nEvery feature is accessible within two clicks. If you need help at any time, click the chat icon in the bottom-right corner.', 'getting_started', 'dashboard', '[]', '["onboarding", "setup", "first steps"]', 1),

(NULL, 'navigating-the-dashboard', 'Navigating Your Dashboard', 'Learn how to use your daily dashboard effectively.', E'# Navigating Your Dashboard\n\nYour dashboard is designed to show you what matters most today:\n\n- **Action Cards** — Documents needing attention, signatures awaiting, upcoming deadlines\n- **Deal Snapshot** — Active deals, pending signatures, closings this month\n- **Quick Actions** — Floating button for common actions like New Transaction or Add Contact\n\n## Tips\n- Click any number in the Deal Snapshot to drill into details\n- Action cards are sorted by urgency — handle the top ones first\n- Use the sidebar to navigate between modules', 'getting_started', 'dashboard', '[]', '["dashboard", "navigation", "overview"]', 2),

-- Transactions
(NULL, 'creating-a-transaction', 'Creating a New Transaction', 'How to create and set up a new real estate transaction.', E'# Creating a New Transaction\n\n1. Click the **+ New Transaction** button on your dashboard or in the Transactions page\n2. Enter the property address — CrestDesk will auto-detect the state for compliance rules\n3. Select the transaction type (Purchase, Sale, Lease, etc.)\n4. Add parties: buyer, seller, agents, lender, title company\n5. Set the key dates: offer date, closing date, contingency deadlines\n6. Upload any existing documents\n\nCrestDesk automatically loads the correct state compliance checklist and required forms based on the property location.', 'transactions', 'transactions', '[]', '["transaction", "new deal", "create"]', 1),

(NULL, 'managing-transaction-documents', 'Managing Transaction Documents', 'How to upload, organize, and track documents in a transaction.', E'# Managing Transaction Documents\n\n## Uploading Documents\n- Drag and drop files directly into the transaction\n- Forward emails with attachments to the transaction''s unique email address\n- CrestDesk automatically classifies the document type\n\n## Organization\n- Documents are auto-organized into folders by type\n- The progress tracker shows which required documents are still missing\n- Signed documents automatically return from the e-signature module\n\n## Compliance\n- Red/Yellow/Green indicators show document status at a glance\n- Missing required documents are flagged automatically\n- State-specific retention periods are applied automatically', 'transactions', 'documents', '[]', '["documents", "upload", "organize", "compliance"]', 2),

-- E-Signatures
(NULL, 'sending-documents-for-signature', 'Sending Documents for Signature', 'How to send documents for electronic signature.', E'# Sending Documents for Signature\n\n1. Open the document you want signed\n2. Click **Send for Signature**\n3. Add signers (they may auto-populate from the transaction)\n4. Place signature fields by dragging them onto the document\n5. Set the signing order if needed\n6. Add an optional message and deadline\n7. Click **Send**\n\nSigners receive an email with a secure link. They can sign on any device — desktop, tablet, or phone.\n\n## Tips\n- Use bulk send to send multiple documents at once\n- Set deadlines with automatic reminders\n- Signed documents auto-return to the transaction', 'e_signatures', 'signing', '[]', '["signature", "esign", "send", "sign"]', 1),

-- Contacts & CRM
(NULL, 'managing-contacts', 'Managing Your Contacts', 'How to add, organize, and track contacts.', E'# Managing Your Contacts\n\n## Adding Contacts\n- Click **+ Add Contact** from the Contacts page\n- Import from CSV, phone, or another CRM (Follow Up Boss, KVCore, LionDesk)\n- Contacts are auto-created from transactions and email interactions\n\n## Organization\n- Use tags and categories to organize contacts (Buyer, Seller, Investor, Past Client)\n- The relationship score shows how strong each relationship is\n- Pipeline view shows where each lead is in your sales process\n\n## Communication\n- All emails, calls, and texts are automatically logged\n- Click the contact card to see their complete interaction history\n- Use follow-up sequences to automate nurturing', 'crm', 'contacts', '[]', '["contacts", "crm", "leads", "clients"]', 1),

-- Compliance
(NULL, 'understanding-compliance-rules', 'Understanding Compliance Rules', 'How CrestDesk enforces federal and state compliance.', E'# Understanding Compliance Rules\n\nCrestDesk automatically enforces compliance at every level:\n\n## Federal Rules (Always Active)\n- **Fair Housing Act** — AI screens all content for discriminatory language\n- **RESPA** — Referral tracking and fee disclosure monitoring\n- **ESIGN Act** — All electronic signatures meet federal requirements\n- **CAN-SPAM** — Automated emails include required disclosures and opt-out links\n- **TCPA** — SMS communications respect consent and time-of-day rules\n\n## State Rules (Auto-Detected)\n- Rules load automatically based on the property''s state\n- Advertising disclaimers, disclosure requirements, and e-signature rules vary by state\n- The stricter rule always wins when federal and state overlap\n\n## Compliance Dashboard\n- Green = compliant, Yellow = needs review, Red = action required\n- Click any flag for a plain-English explanation', 'compliance', 'compliance', '[]', '["compliance", "rules", "fair housing", "state rules"]', 1),

-- Finance
(NULL, 'tracking-commissions', 'Tracking Commissions & Expenses', 'How to manage commissions, expenses, and financial tracking.', E'# Tracking Commissions & Expenses\n\n## Commission Tracking\n- Commission structures are set up per agent by the broker\n- When deals close, commissions are automatically calculated with the correct splits\n- View pending and paid commissions on the Finance dashboard\n\n## Expense Tracking\n- Add deal expenses (photography, staging, inspections) to any transaction\n- Expenses are auto-categorized for tax purposes\n- QuickBooks integration syncs everything automatically\n\n## QuickBooks Integration\n- Connect with one-click OAuth in Settings\n- Commission income and expenses sync automatically\n- Reconciliation dashboard shows CrestDesk vs QuickBooks side-by-side', 'finance', 'finance', '[]', '["commission", "expenses", "quickbooks", "finance"]', 1),

-- Email
(NULL, 'using-the-email-hub', 'Using the Email Hub', 'How to use the unified email inbox and AI assistant.', E'# Using the Email Hub\n\n## Unified Inbox\n- All your connected email accounts appear in one view\n- Emails are automatically tagged to the correct transaction and contact\n- Use folders (Inbox, Sent, Drafts, Starred, Archive, Trash) to organize\n\n## AI Email Assistant\n- Click **AI Reply** to generate a professional response\n- Choose your tone: Professional, Friendly, Casual, or Formal\n- The AI learns your writing style over time\n- AI summaries help you quickly understand long email threads\n\n## Email Templates\n- Use pre-built templates for common scenarios\n- Create custom templates for repetitive communications\n- Templates support dynamic variables (client name, property address, etc.)', 'email', 'email', '[]', '["email", "inbox", "ai assistant", "templates"]', 1),

-- Media Studio
(NULL, 'creating-marketing-materials', 'Creating Marketing Materials', 'How to use the AI Media Studio to generate branded content.', E'# Creating Marketing Materials\n\n## AI Image Generation\n- Generate branded listing graphics (Just Listed, Under Contract, Just Sold)\n- Create social media graphics optimized for each platform\n- Virtual staging for empty rooms in multiple styles\n\n## Asset Library\n- Browse royalty-free stock photos, icons, backgrounds, and music\n- All assets are cleared for commercial use\n- AI recommends assets based on your project\n\n## Compliance\n- All generated content is screened for state advertising rules\n- License numbers and brokerage attribution added automatically\n- Virtual staging disclaimers applied per state requirements', 'media', 'media', '[]', '["media", "images", "marketing", "graphics"]', 1),

-- Social Media
(NULL, 'social-media-automation', 'Social Media Automation', 'How to set up and manage automated social media posting.', E'# Social Media Automation\n\n## Connecting Accounts\n- Go to Social Media > Connections\n- Connect Facebook, Instagram, LinkedIn, and other platforms with one-click OAuth\n\n## Automated Posting\n- Transaction milestones (Just Listed, Under Contract, Sold) auto-generate branded posts\n- AI creates platform-optimized content for each network\n- Choose auto-publish or approval mode\n\n## Content Calendar\n- View all scheduled posts in calendar view\n- Drag and drop to reschedule\n- AI fills gaps with evergreen content (market tips, community features)\n\n## Analytics\n- Track impressions, engagement, and leads from social media\n- AI auto-adjusts strategy based on what performs best', 'social', 'social', '[]', '["social media", "posting", "automation", "marketing"]', 1),

-- Broker-specific
(NULL, 'broker-review-process', 'Broker Review & AI Audit', 'How to review transaction files with AI assistance.', E'# Broker Review & AI Audit\n\n## Review Queue\n- Transactions are prioritized by closing date and compliance status\n- Each file shows a readiness score from 0-100\n- Batch review mode lets you work through files sequentially\n\n## AI Pre-Review\n- AI automatically scans every document before you open the file\n- Issues flagged as Critical (must fix), Warning (should review), or Info\n- Each flag includes the specific rule and jurisdiction reference\n\n## Feedback & Learning\n- Mark AI findings as confirmed or false positive\n- The AI learns from your feedback and improves over time\n- Common flags can be promoted to permanent brokerage rules\n\n## Export\n- One-click export as PDF or ZIP\n- Auto-formatted with table of contents\n- Ready for state regulatory submission', 'management', 'review', '["managing_broker", "principal_broker", "owner"]', '["broker", "review", "audit", "compliance"]', 1),

-- Troubleshooting
(NULL, 'email-connection-issues', 'Troubleshooting Email Connection Issues', 'What to do when email sync stops working.', E'# Troubleshooting Email Connection Issues\n\nIf your email has stopped syncing:\n\n1. Go to **Email > Settings**\n2. Check the connection status next to your account\n3. If it shows "Disconnected", click **Reconnect**\n4. Re-authorize with your email provider (Gmail/Outlook)\n\n## Common Issues\n- **Token expired** — OAuth tokens expire periodically. Simply reconnect.\n- **Password changed** — If you changed your email password, reconnect the account.\n- **2FA enabled** — Make sure app passwords are configured if using 2FA.\n\nIf the issue persists, create a support ticket and our team will help.', 'troubleshooting', 'email', '[]', '["troubleshooting", "email", "connection", "sync"]', 1),

(NULL, 'mls-data-not-updating', 'MLS Data Not Updating', 'What to do when MLS data appears stale.', E'# MLS Data Not Updating\n\nIf listing data seems outdated:\n\n1. Go to **Settings > Connections**\n2. Find your MLS connection and check the last sync time\n3. Click **Sync Now** to force an immediate update\n4. If sync fails, verify your MLS credentials are still valid\n\n## Notes\n- MLS data typically refreshes every 15-30 minutes\n- Some MLS boards have rate limits that may delay updates\n- New listings may take up to 1 hour to appear after MLS entry', 'troubleshooting', 'connections', '[]', '["mls", "data", "sync", "listings"]', 2),

-- CrestAI specific
(NULL, 'using-crestai-copilot', 'Using CrestAI — Your AI Deal Assistant', 'How to use CrestAI to manage deals and get instant answers.', E'# Using CrestAI — Your AI Deal Assistant\n\nCrestAI is your AI copilot that knows everything about your deals.\n\n## Asking Questions\n- Type natural language questions: "What''s the status of the Johnson deal?"\n- CrestAI answers from your actual transaction data\n- Ask about deadlines, missing documents, compliance status, and more\n\n## Smart Alerts\n- Deadline monitoring tracks all contingencies across your transactions\n- Missing document alerts flag items needed before closing\n- Compliance warnings highlight state-specific issues\n\n## Deal Overview\n- View a summary of all active deals in one place\n- Each deal shows status, closing date, readiness score, and next actions\n\n## Tips\n- Start with the suggested queries on the CrestAI page\n- The more specific your question, the better the answer\n- Rate responses with thumbs up/down to help improve accuracy', 'getting_started', 'ai', '[]', '["crestai", "copilot", "ai", "assistant", "deals"]', 3);
