-- Migration: 0096_phase11_seed_breach_rules
-- Description: Seed 50 states + DC breach notification rules

INSERT INTO breach_notification_rules (state_code, state_name, notification_deadline_days, attorney_general_required, consumer_reporting_required, threshold_individuals, statute_reference, summary)
VALUES
  ('AL', 'Alabama', 45, true, false, NULL, 'Ala. Code § 8-38-1 et seq.', 'Notification to AG and affected individuals within 45 days of determination'),
  ('AK', 'Alaska', NULL, true, false, NULL, 'Alaska Stat. § 45.48.010 et seq.', 'Notification to AG and affected individuals in most expedient time possible'),
  ('AZ', 'Arizona', 45, true, false, 1000, 'Ariz. Rev. Stat. § 18-552', 'Notification within 45 days; AG notification if 1,000+ individuals affected'),
  ('AR', 'Arkansas', NULL, false, false, NULL, 'Ark. Code § 4-110-101 et seq.', 'Notification in most expedient time and manner possible'),
  ('CA', 'California', NULL, true, false, 500, 'Cal. Civ. Code § 1798.82', 'Most expedient time possible; AG notification if 500+ residents affected'),
  ('CO', 'Colorado', 30, true, false, 500, 'Colo. Rev. Stat. § 6-1-716', 'Notification within 30 days; AG notification if 500+ residents affected'),
  ('CT', 'Connecticut', 60, true, false, NULL, 'Conn. Gen. Stat. § 36a-701b', 'Notification within 60 days; AG notification required'),
  ('DE', 'Delaware', 60, true, false, 500, 'Del. Code tit. 6 § 12B-101 et seq.', 'Notification within 60 days; AG notification if 500+ residents affected'),
  ('FL', 'Florida', 30, true, false, 500, 'Fla. Stat. § 501.171', 'Notification within 30 days; AG notification if 500+ residents affected'),
  ('GA', 'Georgia', NULL, false, false, NULL, 'Ga. Code § 10-1-912', 'Most expedient time possible, without unreasonable delay'),
  ('HI', 'Hawaii', NULL, true, false, NULL, 'Haw. Rev. Stat. § 487N-2', 'Notification without unreasonable delay; AG notification required'),
  ('ID', 'Idaho', NULL, false, false, NULL, 'Idaho Code § 28-51-104 et seq.', 'Most expedient time possible, without unreasonable delay'),
  ('IL', 'Illinois', NULL, true, false, 500, '815 ILCS 530/10', 'Most expedient time possible; AG notification if 500+ residents affected'),
  ('IN', 'Indiana', NULL, true, false, NULL, 'Ind. Code § 24-4.9-3-3', 'Without unreasonable delay; AG notification required'),
  ('IA', 'Iowa', NULL, true, false, 500, 'Iowa Code § 715C.2', 'Most expedient time possible; AG notification if 500+ residents affected'),
  ('KS', 'Kansas', NULL, false, false, NULL, 'Kan. Stat. § 50-7a01 et seq.', 'Most expedient time possible, without unreasonable delay'),
  ('KY', 'Kentucky', NULL, true, false, NULL, 'KRS § 365.732', 'Without unreasonable delay; AG notification required'),
  ('LA', 'Louisiana', 60, true, false, NULL, 'La. Rev. Stat. § 51:3074', 'Notification within 60 days; AG notification required'),
  ('ME', 'Maine', 30, true, false, NULL, 'Me. Rev. Stat. tit. 10 § 1348', 'Notification within 30 days; AG notification required'),
  ('MD', 'Maryland', 45, true, false, NULL, 'Md. Code Com. Law § 14-3504', 'Notification within 45 days; AG notification required'),
  ('MA', 'Massachusetts', NULL, true, true, NULL, 'Mass. Gen. Laws ch. 93H § 3', 'Notification as soon as practicable; AG and consumer reporting agency required'),
  ('MI', 'Michigan', NULL, false, false, NULL, 'Mich. Comp. Laws § 445.72', 'Without unreasonable delay'),
  ('MN', 'Minnesota', NULL, true, false, 500, 'Minn. Stat. § 325E.61', 'Most expedient time possible; AG notification if 500+ residents affected'),
  ('MS', 'Mississippi', NULL, true, false, NULL, 'Miss. Code § 75-24-29', 'Without unreasonable delay; AG notification required'),
  ('MO', 'Missouri', NULL, true, false, NULL, 'Mo. Rev. Stat. § 407.1500', 'Without unreasonable delay; AG notification required'),
  ('MT', 'Montana', NULL, true, false, NULL, 'Mont. Code § 30-14-1704', 'Without unreasonable delay; AG notification required'),
  ('NE', 'Nebraska', NULL, true, false, NULL, 'Neb. Rev. Stat. § 87-801 et seq.', 'Without unreasonable delay; AG notification required'),
  ('NV', 'Nevada', NULL, true, false, NULL, 'Nev. Rev. Stat. § 603A.220', 'Without unreasonable delay; AG notification required'),
  ('NH', 'New Hampshire', NULL, true, false, NULL, 'N.H. Rev. Stat. § 359-C:20', 'Without unreasonable delay; AG notification required'),
  ('NJ', 'New Jersey', NULL, true, false, NULL, 'N.J. Stat. § 56:8-163', 'Without unreasonable delay; AG notification required'),
  ('NM', 'New Mexico', 45, true, false, NULL, 'N.M. Stat. § 57-12C-1 et seq.', 'Notification within 45 days; AG notification required'),
  ('NY', 'New York', NULL, true, false, NULL, 'N.Y. Gen. Bus. Law § 899-aa', 'Most expedient time possible; AG, DFS, and DOS notification required'),
  ('NC', 'North Carolina', NULL, true, false, NULL, 'N.C. Gen. Stat. § 75-65', 'Without unreasonable delay; AG notification required'),
  ('ND', 'North Dakota', NULL, true, false, 250, 'N.D. Cent. Code § 51-30-01 et seq.', 'Most expedient time possible; AG notification if 250+ residents affected'),
  ('OH', 'Ohio', NULL, true, false, NULL, 'Ohio Rev. Code § 1349.19', 'Most expedient time possible; AG notification required'),
  ('OK', 'Oklahoma', NULL, true, false, NULL, 'Okla. Stat. tit. 24 § 163', 'Without unreasonable delay; AG notification required'),
  ('OR', 'Oregon', 45, true, false, 250, 'ORS § 646A.604', 'Notification within 45 days; AG notification if 250+ residents affected'),
  ('PA', 'Pennsylvania', NULL, true, false, NULL, '73 Pa. Stat. § 2303', 'Without unreasonable delay; AG notification required'),
  ('RI', 'Rhode Island', 30, true, false, 500, 'R.I. Gen. Laws § 11-49.3-4', 'Notification within 30 days; AG notification if 500+ residents affected'),
  ('SC', 'South Carolina', NULL, true, true, NULL, 'S.C. Code § 39-1-90', 'Without unreasonable delay; AG and consumer reporting agency required'),
  ('SD', 'South Dakota', 60, true, false, 250, 'S.D. Codified Laws § 22-40-19 et seq.', 'Notification within 60 days; AG notification if 250+ residents affected'),
  ('TN', 'Tennessee', 45, true, false, NULL, 'Tenn. Code § 47-18-2107', 'Notification within 45 days; AG notification required'),
  ('TX', 'Texas', 60, true, false, 250, 'Tex. Bus. & Com. Code § 521.053', 'Notification within 60 days; AG notification if 250+ residents affected'),
  ('UT', 'Utah', NULL, true, false, NULL, 'Utah Code § 13-44-202', 'Without unreasonable delay; AG notification required'),
  ('VT', 'Vermont', 45, true, false, NULL, 'Vt. Stat. tit. 9 § 2435', 'Notification within 45 days; AG notification required'),
  ('VA', 'Virginia', 60, true, false, NULL, 'Va. Code § 18.2-186.6', 'Without unreasonable delay (no later than 60 days); AG notification required'),
  ('WA', 'Washington', 30, true, false, 500, 'Wash. Rev. Code § 19.255.010', 'Notification within 30 days; AG notification if 500+ residents affected'),
  ('WV', 'West Virginia', NULL, false, false, NULL, 'W. Va. Code § 46A-2A-101 et seq.', 'Without unreasonable delay'),
  ('WI', 'Wisconsin', 45, true, false, NULL, 'Wis. Stat. § 134.98', 'Notification within 45 days; AG notification required'),
  ('WY', 'Wyoming', NULL, false, false, NULL, 'Wyo. Stat. § 40-12-501 et seq.', 'Most expedient time possible'),
  ('DC', 'District of Columbia', NULL, true, false, NULL, 'D.C. Code § 28-3852', 'Most expedient time possible; AG notification required')
ON CONFLICT (state_code) DO NOTHING;
