import { pgTable, uuid, text, timestamp, varchar, jsonb, boolean, integer } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';

export const emails = pgTable('emails', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
  emailAccountId: uuid('email_account_id').notNull(),
  agentId: uuid('agent_id').notNull(),
  transactionId: uuid('transaction_id'),
  contactId: uuid('contact_id'),
  threadId: varchar('thread_id', { length: 200 }),
  messageId: varchar('message_id', { length: 300 }),
  inReplyTo: varchar('in_reply_to', { length: 300 }),
  direction: varchar('direction', { length: 10 }).notNull(),
  fromAddress: varchar('from_address', { length: 255 }).notNull(),
  fromName: varchar('from_name', { length: 200 }),
  toAddresses: jsonb('to_addresses').notNull(),
  ccAddresses: jsonb('cc_addresses'),
  bccAddresses: jsonb('bcc_addresses'),
  subject: text('subject'),
  bodyHtml: text('body_html'),
  bodyText: text('body_text'),
  snippet: varchar('snippet', { length: 500 }),
  hasAttachments: boolean('has_attachments').default(false),
  attachments: jsonb('attachments'),
  labels: jsonb('labels'),
  priority: varchar('priority', { length: 20 }).default('normal'),
  isRead: boolean('is_read').default(false),
  isStarred: boolean('is_starred').default(false),
  isArchived: boolean('is_archived').default(false),
  isDraft: boolean('is_draft').default(false),
  isSent: boolean('is_sent').default(false),
  autoFiledTo: varchar('auto_filed_to', { length: 50 }),
  aiSuggestedActions: jsonb('ai_suggested_actions'),
  complianceStatus: varchar('compliance_status', { length: 30 }),
  complianceIssues: jsonb('compliance_issues'),
  sentAt: timestamp('sent_at', { withTimezone: true }),
  receivedAt: timestamp('received_at', { withTimezone: true }),
  metadata: jsonb('metadata'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});
