import { pgTable, uuid, text, timestamp, varchar, jsonb, integer } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';
import { users } from './users';

export const mediaAssets = pgTable('media_assets', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
  agentId: uuid('agent_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  assetType: varchar('asset_type', { length: 30 }).notNull(),
  mediaType: varchar('media_type', { length: 50 }).notNull(),
  title: varchar('title', { length: 300 }).notNull(),
  description: text('description'),
  filePath: text('file_path').notNull(),
  thumbnailPath: text('thumbnail_path'),
  fileSize: integer('file_size'),
  mimeType: varchar('mime_type', { length: 100 }),
  dimensions: jsonb('dimensions'),
  duration: integer('duration'),
  generatedByService: varchar('generated_by_service', { length: 50 }),
  generationPrompt: text('generation_prompt'),
  generationParams: jsonb('generation_params'),
  transactionId: uuid('transaction_id'),
  status: varchar('status', { length: 30 }).notNull().default('draft'),
  complianceStatus: varchar('compliance_status', { length: 30 }).default('pending'),
  complianceIssues: jsonb('compliance_issues'),
  complianceCheckedAt: timestamp('compliance_checked_at', { withTimezone: true }),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  publishedPlatforms: jsonb('published_platforms'),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  metadata: jsonb('metadata'),
  tags: jsonb('tags'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});
