import { pgTable, uuid, varchar, text, jsonb, integer, timestamp } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';
import { users } from './users';

export const socialPosts = pgTable('social_posts', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
  agentId: uuid('agent_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  socialAccountId: uuid('social_account_id'),
  transactionId: uuid('transaction_id'),
  campaignId: uuid('campaign_id'),
  postType: varchar('post_type', { length: 50 }).notNull(),
  platform: varchar('platform', { length: 30 }).notNull(),
  content: text('content').notNull(),
  hashtags: jsonb('hashtags').default([]),
  mediaAssetIds: jsonb('media_asset_ids').default([]),
  contentVariations: jsonb('content_variations').default([]),
  status: varchar('status', { length: 30 }).notNull().default('draft'),
  scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  platformPostId: varchar('platform_post_id', { length: 255 }),
  platformPostUrl: text('platform_post_url'),
  complianceStatus: varchar('compliance_status', { length: 30 }).default('pending'),
  complianceIssues: jsonb('compliance_issues'),
  complianceCheckedAt: timestamp('compliance_checked_at', { withTimezone: true }),
  approvedBy: uuid('approved_by'),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  rejectionReason: text('rejection_reason'),
  rejectedBy: uuid('rejected_by'),
  rejectedAt: timestamp('rejected_at', { withTimezone: true }),
  impressions: integer('impressions').default(0),
  reach: integer('reach').default(0),
  likes: integer('likes').default(0),
  comments: integer('comments').default(0),
  shares: integer('shares').default(0),
  clicks: integer('clicks').default(0),
  engagement: jsonb('engagement').default({}),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});
